services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 8080:8080
    environment:
      - PORT=${PORT}
      - AUTH_API_ADDRESS=${AUTH_API_ADDRESS}
      - TODOS_API_ADDRESS=${TODOS_API_ADDRESS}
      - ZIPKIN_URL=${ZIPKIN_URL}
    depends_on:
      - zipkin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`chukwukelu.online`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    restart: on-failure

  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    container_name: auth-api
    ports:
      - 8081:8081
    environment:
      - AUTH_API_PORT=${AUTH_API_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - USERS_API_ADDRESS=${USERS_API_ADDRESS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`chukwukelu.online`) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=le"
      - "traefik.http.services.auth.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/api/auth"
      - "traefik.http.routers.auth.middlewares=auth-strip"
    restart: on-failure

  todos-api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    container_name: todos-api
    ports:
      - 8082:8082
    environment:
      - TODO_API_PORT=${TODO_API_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
      - ZIPKIN_URL=${ZIPKIN_URL}
    depends_on:
      - redis-queue
      - zipkin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos.rule=Host(`chukwukelu.online`) && PathPrefix(`/api/todos`)"
      - "traefik.http.routers.todos.entrypoints=websecure"
      - "traefik.http.routers.todos.tls.certresolver=le"
      - "traefik.http.services.todos.loadbalancer.server.port=8082"
      - "traefik.http.middlewares.todos-strip.stripprefix.prefixes=/api/todos"
      - "traefik.http.routers.todos.middlewares=todos-strip"
    restart: on-failure

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    container_name: users-api
    ports:
      - 8083:8083
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`chukwukelu.online`) && PathPrefix(`/api/users`)"
      - "traefik.http.routers.users.entrypoints=websecure"
      - "traefik.http.routers.users.tls.certresolver=le"
      - "traefik.http.services.users.loadbalancer.server.port=8083"
      - "traefik.http.middlewares.users-strip.stripprefix.prefixes=/api/users"
      - "traefik.http.routers.users.middlewares=users-strip"
    restart: on-failure

  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile
    container_name: log-message-processor
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
    depends_on:
      - redis-queue
    restart: on-failure

  redis-queue:
    image: redis:7-alpine
    container_name: redis-queue
    ports:
      - 6379:6379
    restart: on-failure

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zipkin.rule=Host(`chukwukelu.online`) && PathPrefix(`/zipkin`)"
      - "traefik.http.routers.zipkin.entrypoints=websecure"
      - "traefik.http.routers.zipkin.tls.certresolver=le"
      - "traefik.http.services.zipkin.loadbalancer.server.port=9411"
      - "traefik.http.middlewares.zipkin-strip.stripprefix.prefixes=/zipkin"
      - "traefik.http.routers.zipkin.middlewares=zipkin-strip"
    restart: on-failure

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Redirect HTTP â†’ HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=chukwukeluoo@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

      # Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "443:443"
      - "8084:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: on-failure